### ISSUE TITLE
prokka split errors in phylogenetic_analysis workflow lines 17 & 22

### ISSUE THREAD

**Issue by DrB-S** [UPHL-BioNGS/Grandeur#38]
Command-line:
/data/Sequence_analysis/nextflowedge run UPHL-BioNGS/Grandeur -profile singularity,msa --medcpus 30 --maxcpus 40
**## I am only feeding it gff files -- no fasta or fastq files**

Errors:
```
Feb-16 13:49:41.617 [Actor Thread 114] ERROR nextflow.extension.OperatorImpl - @unknown
java.lang.NullPointerException: Cannot invoke method split() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Script_cc7be3c9$_runScript_closure1$_closure2$_closure5.doCall(Script_cc7be3c9:22)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:57)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
        at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
        at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
        at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
        at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
        at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Feb-16 13:49:41.617 [Actor Thread 128] DEBUG nextflow.file.SortFileCollector - FileCollector temp dir not removed: null
Feb-16 13:49:41.617 [Actor Thread 113] ERROR nextflow.extension.OperatorImpl - @unknown
java.lang.NullPointerException: Cannot invoke method split() on null object
        at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:44)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:34)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at Script_cc7be3c9$_runScript_closure1$_closure2$_closure3.doCall(Script_cc7be3c9:17)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:38)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at nextflow.extension.MapOp$_apply_closure1.doCall(MapOp.groovy:57)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
        at groovyx.gpars.dataflow.operator.DataflowOperatorActor.onMessage(DataflowOperatorActor.java:108)
        at groovyx.gpars.actor.impl.SDAClosure$1.call(SDAClosure.java:43)
        at groovyx.gpars.actor.AbstractLoopingActor.runEnhancedWithoutRepliesOnMessages(AbstractLoopingActor.java:293)
        at groovyx.gpars.actor.AbstractLoopingActor.access$400(AbstractLoopingActor.java:30)
        at groovyx.gpars.actor.AbstractLoopingActor$1.handleMessage(AbstractLoopingActor.java:93)
        at groovyx.gpars.util.AsyncMessagingCore.run(AsyncMessagingCore.java:132)
[-        ] process > de_novo_alignment:spades                      -
[-        ] process > min_hash_distance:mash                        -
[-        ] process > de_novo_alignment:bbduk                       -
[-        ] process > de_novo_alignment:fastp                       -
[-        ] process > de_novo_alignment:spades                      -
[-        ] process > min_hash_distance:mash                        -
[-        ] process > average_nucleotide_identity:species           -
[-        ] process > average_nucleotide_identity:datasets_summary  -
[-        ] process > average_nucleotide_identity:datasets_download -
[-        ] process > average_nucleotide_identity:fastani           -
[-        ] process > information:size                              -
[-        ] process > information:fastqscan                         -
[-        ] process > information:fastqc                            -
[-        ] process > information:mlst                              -
[-        ] process > information:quast                             -
[-        ] process > information:plasmidfinder                     -
[-        ] process > information:flag                              -
[-        ] process > information:amrfinderplus                     -
[-        ] process > information:kleborate                         -
[-        ] process > information:seqsero2                          -
[-        ] process > information:serotypefinder                    -
[-        ] process > information:shigatyper                        -
[-        ] process > phylogenetic_analysis:prokka                  -
[-        ] process > phylogenetic_analysis:roary                   -
[-        ] process > phylogenetic_analysis:iqtree2                 -
[-        ] process > phylogenetic_analysis:snp_dists               -
[-        ] process > report:multiqc                                -
[-        ] process > report:names                                  -
[-        ] process > report:summary                                [  0%] 0 of 1
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00099.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00103.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00111.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00130.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00132.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00213.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00224.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00228.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00253.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00007.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00066.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00176.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00185.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00202.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00274.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00275.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00289.gff
gff file : /data/Sequence_analysis/Grandeur/Analyses/311112_Boswell/gff/2022LN-00001.gff
Cannot invoke method split() on null object

 -- Check script '/app/becksts/.nextflow/assets/UPHL-BioNGS/Grandeur/./subworkflows/phylogenetic_analysis.nf' at line: 22 or see '.nextflow.log' file for more details
Cannot invoke method split() on null object

 -- Check script '/app/becksts/.nextflow/assets/UPHL-BioNGS/Grandeur/./subworkflows/phylogenetic_analysis.nf' at line: 17 or see '.nextflow.log' file for more details
```
```
Below are the two offending lines in phylogenetic_analysis.nf:
 main:
    for_prokka = Channel.empty()
    if (params.extras) {
      ch_top_hit
**#17 =>**        .map { it -> tuple( it[0] , [ it[1].split("/")[1].split("_")[0], it[1].split("/")[1].split("_")[1]] )}
        .set { ch_organism }

      if ( params.fastani_include ) {
        ch_top_hit
**#22 =>**          .map { it -> tuple( it[1].split("/")[1].split("_", 3)[2].replaceAll(~/.fna/,""), it[2], it[1].split("/")[1].split("_")[0, 1]) }
          .groupTuple(by: 0)
          .map { it -> tuple( it[0], it[1][0], it[2][0] ) }
          .unique()
          .set { ch_representative }

        for_prokka = for_prokka.mix(ch_representative)
      }
```

**Comment by DrB-S** [comment]
Grandeur Version: 3.0.20230205
Nextflow Version: 22.10.6.5843

**Comment by erinyoung** [comment]
Thanks for letting me know!

It looks like it's creating a null value for the fasta file channels - which are causing errors downstream. I'll work on getting that fixed.

In the meantime, I recommend using the `just_msa` profile.
```
/data/Sequence_analysis/nextflowedge run UPHL-BioNGS/Grandeur -profile singularity,just_msa --medcpus 30 --maxcpus 40
## I am only feeding it gff files -- no fasta or fastq files
```

**Comment by DrB-S** [comment]
I would do that, but I need the prokka output, so that I can grab specific plasmid gene regions for comparison.

**Comment by erinyoung** [comment]
The gff files should have been created by prokka. They won't be run through prokka again. 

If you need the files to go through prokka, you'll need fasta/contig files (or fastq files that will go through some reference-free alignment).

**Comment by DrB-S** [comment]
I had a feeling that might be the case, and I am in the process of setting that up. Will I still have the gene info if I don't use a reference?

**Comment by erinyoung** [comment]
In theory, yes. 

Grandeur is completely reference-free, so prokka will only annotate fasta files with whatever is in its 4 year old database.

If you need something more current, I recommend [bakta](https://github.com/oschwengers/bakta) (although it requires a large database) or PGAP (which you can run on fasta files via NCBI genomes.

**Comment by DrB-S** [comment]
Doesn't Grandeur use the outgroup to annotate if I supply one?

**Comment by erinyoung** [comment]
No, the outgroup is only used by iqtree2 when constructing phylogenetic trees.
